-- public.cel_certificado definition

-- Drop table

-- DROP TABLE public.cel_certificado;

CREATE TABLE public.cel_certificado (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	firma text NOT NULL,
	clave varchar NOT NULL,
	nombre_certificado varchar NOT NULL,
	activo bool DEFAULT true NOT NULL,
	CONSTRAINT celcertificado_pk PRIMARY KEY (id)
);


-- public.cel_info_tributaria definition

-- Drop table

-- DROP TABLE public.cel_info_tributaria;

CREATE TABLE public.cel_info_tributaria (
	id int2 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	razon_social varchar NOT NULL,
	nombre_comercial varchar NOT NULL,
	ruc varchar NOT NULL,
	direccion_matriz varchar NOT NULL,
	contribuyente_especial varchar NOT NULL,
	obligado_contabilidad bool NOT NULL,
	contribuyente_rimpe varchar NULL,
	CONSTRAINT cel_info_tributaria_pk PRIMARY KEY (id)
);


-- public.cel_log_documento definition

-- Drop table

-- DROP TABLE public.cel_log_documento;

CREATE TABLE public.cel_log_documento (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo_documento int4 NOT NULL,
	estado int4 NOT NULL,
	mensaje varchar NOT NULL,
	autorizacion varchar NOT NULL,
	xml_firmado text NOT NULL,
	ambiente int4 NOT NULL,
	tipo_emision int4 NOT NULL,
	fecha_hora date DEFAULT now() NOT NULL,
	CONSTRAINT cellog_documentos_pk PRIMARY KEY (id)
);


-- public.cel_secuencia_sri definition

-- Drop table

-- DROP TABLE public.cel_secuencia_sri;

CREATE TABLE public.cel_secuencia_sri (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	tipo_documento varchar NOT NULL,
	establecimiento varchar NOT NULL,
	punto_de_emision varchar NOT NULL,
	secuencia_actual int4 DEFAULT 1 NOT NULL,
	estado bool DEFAULT true NOT NULL,
	CONSTRAINT celsecuencia_sri_pk PRIMARY KEY (id)
);
CREATE INDEX idx_cel_secuencia_sri_tipo ON public.cel_secuencia_sri USING btree (tipo_documento);


-- public.fac_cliente definition

-- Drop table

-- DROP TABLE public.fac_cliente;

CREATE TABLE public.fac_cliente (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar NOT NULL,
	apellido varchar NOT NULL,
	cedula_ruc varchar NOT NULL,
	telefono_celular varchar NULL,
	email varchar NULL,
	fecha_cumpleanios int4 NULL,
	direccion varchar NULL,
	fecha_registro date DEFAULT now() NOT NULL,
	usuario_registro varchar NOT NULL,
	CONSTRAINT cliente_pk PRIMARY KEY (id)
);
CREATE INDEX idx_fac_cliente_cedula_ruc ON public.fac_cliente USING btree (cedula_ruc);


-- public.fac_producto definition

-- Drop table

-- DROP TABLE public.fac_producto;

CREATE TABLE public.fac_producto (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar NOT NULL,
	grupo varchar NULL,
	valor numeric NOT NULL,
	codigo_iva int2 NOT NULL,
	activo bool DEFAULT true NOT NULL,
	orden_aparicion int2 DEFAULT 0 NOT NULL,
	pedido_a_cocina bool DEFAULT false NULL,
	valor_doncho numeric NOT NULL,
	CONSTRAINT producto_pk PRIMARY KEY (id)
);
CREATE INDEX idx_fac_producto_activo ON public.fac_producto USING btree (activo);
CREATE INDEX idx_fac_producto_grupo ON public.fac_producto USING btree (grupo);


-- public.fac_secuencia_dia definition

-- Drop table

-- DROP TABLE public.fac_secuencia_dia;

CREATE TABLE public.fac_secuencia_dia (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha int4 NOT NULL,
	secuencia int4 NOT NULL,
	CONSTRAINT secuencia_pk PRIMARY KEY (id)
);


-- public.gen_catalogo definition

-- Drop table

-- DROP TABLE public.gen_catalogo;

CREATE TABLE public.gen_catalogo (
	id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar NOT NULL,
	activo bool NOT NULL,
	CONSTRAINT gen_catalogo_pk PRIMARY KEY (id)
);


-- public.gen_feriado definition

-- Drop table

-- DROP TABLE public.gen_feriado;

CREATE TABLE public.gen_feriado (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	fecha int4 NOT NULL,
	CONSTRAINT gen_feriado_pk PRIMARY KEY (id)
);


-- public.gen_parametro definition

-- Drop table

-- DROP TABLE public.gen_parametro;

CREATE TABLE public.gen_parametro (
	id varchar NOT NULL,
	descripcion varchar NOT NULL,
	valor varchar NOT NULL,
	CONSTRAINT genparametros_pk PRIMARY KEY (id)
);


-- public.gen_usuario definition

-- Drop table

-- DROP TABLE public.gen_usuario;

CREATE TABLE public.gen_usuario (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nombre varchar NOT NULL,
	"password" varchar NOT NULL,
	CONSTRAINT usuario_pk PRIMARY KEY (id)
);


-- public.fac_orden definition

-- Drop table

-- DROP TABLE public.fac_orden;

CREATE TABLE public.fac_orden (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	clienteid int4 NOT NULL,
	fecha_integer int4 NOT NULL,
	secuencial int4 NOT NULL,
	fecha timestamp DEFAULT now() NOT NULL,
	tipo_pago varchar NOT NULL,
	total_orden numeric NOT NULL,
	total_sin_impuestos numeric NOT NULL,
	impuesto_valor numeric NOT NULL,
	impuesto_base_imponible numeric NOT NULL,
	impuesto_codigo int2 NOT NULL,
	impuesto_codigo_porcentaje int2 NOT NULL,
	usuario_registro varchar NOT NULL,
	es_factura bool DEFAULT false NOT NULL,
	numero_factura varchar NULL,
	clave_numero_autorizacion varchar DEFAULT ''::character varying NOT NULL,
	establecimiento varchar DEFAULT ''::character varying NOT NULL,
	punto_emision varchar DEFAULT ''::character varying NOT NULL,
	documento_pago varchar DEFAULT ''::character varying NOT NULL,
	impuesto_porcentaje numeric NOT NULL,
	es_nota_credito bool DEFAULT false NULL,
	nota_credito_numero_nota_credito varchar NULL,
	nota_credito_clave_numero_autorizacion varchar NULL,
	nota_credito_motivo varchar NULL,
	nota_credito_fecha timestamp DEFAULT now() NULL,
	CONSTRAINT orden_pk PRIMARY KEY (id),
	CONSTRAINT orden_cliente_fk FOREIGN KEY (clienteid) REFERENCES public.fac_cliente(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_fac_orden_clienteid ON public.fac_orden USING btree (clienteid);
CREATE INDEX idx_fac_orden_fecha_integer ON public.fac_orden USING btree (fecha_integer);


-- public.gen_catalogo_detalle definition

-- Drop table

-- DROP TABLE public.gen_catalogo_detalle;

CREATE TABLE public.gen_catalogo_detalle (
	id int2 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START 1 CACHE 1 NO CYCLE) NOT NULL,
	catalogoid int2 NOT NULL,
	codigo varchar NOT NULL,
	valor varchar NOT NULL,
	activo bool NOT NULL,
	CONSTRAINT gen_catalogo_detalle_pk PRIMARY KEY (id),
	CONSTRAINT gen_catalogo_detalle_gen_catalogo_fk FOREIGN KEY (catalogoid) REFERENCES public.gen_catalogo(id)
);


-- public.fac_detalle_orden definition

-- Drop table

-- DROP TABLE public.fac_detalle_orden;

CREATE TABLE public.fac_detalle_orden (
	id int4 GENERATED ALWAYS AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ordenid int4 NOT NULL,
	productoid int2 NOT NULL,
	cantidad int2 NOT NULL,
	precio_unitario numeric NOT NULL,
	impuesto_codigo int2 NOT NULL,
	precio_total numeric NOT NULL,
	pedido_a_cocina bool DEFAULT false NOT NULL,
	impuesto_codigo_porcentaje int2 NOT NULL,
	impuesto_valor numeric DEFAULT 0 NOT NULL,
	impuesto_tarifa int2 NOT NULL,
	CONSTRAINT detalle_orden_pk PRIMARY KEY (id),
	CONSTRAINT detalle_orden_orden_fk FOREIGN KEY (ordenid) REFERENCES public.fac_orden(id) ON DELETE RESTRICT ON UPDATE CASCADE,
	CONSTRAINT detalle_orden_producto_fk FOREIGN KEY (productoid) REFERENCES public.fac_producto(id) ON DELETE RESTRICT ON UPDATE CASCADE
);
CREATE INDEX idx_fac_detalle_orden_ordenid ON public.fac_detalle_orden USING btree (ordenid);
CREATE INDEX idx_fac_detalle_orden_productoid ON public.fac_detalle_orden USING btree (productoid);